# Generated by Django 4.2.6 on 2023-10-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('serializer_name', models.CharField(max_length=32)),
                ('achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
            ],
            options={
                'verbose_name': 'событие в новостной ленте',
                'verbose_name_plural': 'события в новостной ленте',
            },
        ),
    ]
