# Generated by Django 4.2.6 on 2023-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_feedevent_serializer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedevent',
            name='title',
            field=models.CharField(default='sfsdf', max_length=32, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
